
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/egou
    username: root
    password: root
    tomcat:
      max-active: 2
  application:
    name: all-interface
mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: all-interface #显示的名字而已
    prefer-ip-address: true
server:
  port: 8888